---
# CIS 1.4 - Secure Boot Settings
# Configures bootloader security settings

- name: Set bootloader config permissions
  file:
    path: /boot/grub/grub.cfg
    owner: root
    group: root
    mode: '0600'
  when: ansible_facts['os_family'] == "Debian"

